export enum DocumentType {
  PAYMENT_RECEIPT = 'PAYMENT_RECEIPT',
  INVOICE = 'INVOICE',
  SERVICE_ORDER = 'SERVICE_ORDER',
  MANUAL_NUMBER = 'MANUAL_NUMBER',
  MEDICAL_CERTIFICATE = 'MEDICAL_CERTIFICATE',
  MEETING_MINUTES = 'MEETING_MINUTES',
}